### ISSUE TITLE
CMake packaging

### ISSUE THREAD

**Issue by jcarpent** [mayataka/idocp#35]
Dear @mayataka,

Very nice job. Your package seems really interesting, going in the common trend of developping real-time MPC for robots.
And I really appreciate that you rely on Pinocchio for computing the dynamics and their derivatives.

Among other things, I think the way you link your package to Pinocchio through CMake can now be updated. 
You are no more obliged to rely on the pkg-config linkage procedure.

And again, if you need more featues from Pinocchio's side, do not hesitate to request them and/or to implement them inside Pinocchio. We do love external contributions: it makes our lives simpler.

Best,
Justin

**Comment by mayataka** [comment]
Dear @jcarpent 

Thank you very for letting me know the linkage way of Pinocchio.
And thanks to a lot for your kind comments and the wonderful repository Pinocchio again.

Regards, 
Sotaro Katayama
